//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:39:05 PM NOVT 
//


package ru.develop.anketamanager.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnketaMarketInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnketaMarketInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="DirectPurchase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PurchasesCompetitors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupplierCompetitors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountOutlets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalTurnover" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ShareOfTotalTerema" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DiscountsCompetitors" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AdvCompaniesCompetitors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PromoBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnketaMarketInfo", propOrder = {

})
public class AnketaMarketInfo {

    @XmlElement(name = "DirectPurchase", required = true)
    protected String directPurchase;
    @XmlElement(name = "PurchasesCompetitors", required = true)
    protected String purchasesCompetitors;
    @XmlElement(name = "SupplierCompetitors", required = true)
    protected String supplierCompetitors;
    @XmlElement(name = "CountOutlets")
    protected int countOutlets;
    @XmlElement(name = "TotalTurnover", required = true)
    protected BigDecimal totalTurnover;
    @XmlElement(name = "ShareOfTotalTerema")
    protected int shareOfTotalTerema;
    @XmlElement(name = "DiscountsCompetitors")
    protected int discountsCompetitors;
    @XmlElement(name = "AdvCompaniesCompetitors", required = true)
    protected String advCompaniesCompetitors;
    @XmlElement(name = "PromoBrand", required = true)
    protected String promoBrand;

    /**
     * Gets the value of the directPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectPurchase() {
        return directPurchase;
    }

    /**
     * Sets the value of the directPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectPurchase(String value) {
        this.directPurchase = value;
    }

    /**
     * Gets the value of the purchasesCompetitors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchasesCompetitors() {
        return purchasesCompetitors;
    }

    /**
     * Sets the value of the purchasesCompetitors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchasesCompetitors(String value) {
        this.purchasesCompetitors = value;
    }

    /**
     * Gets the value of the supplierCompetitors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierCompetitors() {
        return supplierCompetitors;
    }

    /**
     * Sets the value of the supplierCompetitors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierCompetitors(String value) {
        this.supplierCompetitors = value;
    }

    /**
     * Gets the value of the countOutlets property.
     * 
     */
    public int getCountOutlets() {
        return countOutlets;
    }

    /**
     * Sets the value of the countOutlets property.
     * 
     */
    public void setCountOutlets(int value) {
        this.countOutlets = value;
    }

    /**
     * Gets the value of the totalTurnover property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTurnover() {
        return totalTurnover;
    }

    /**
     * Sets the value of the totalTurnover property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTurnover(BigDecimal value) {
        this.totalTurnover = value;
    }

    /**
     * Gets the value of the shareOfTotalTerema property.
     * 
     */
    public int getShareOfTotalTerema() {
        return shareOfTotalTerema;
    }

    /**
     * Sets the value of the shareOfTotalTerema property.
     * 
     */
    public void setShareOfTotalTerema(int value) {
        this.shareOfTotalTerema = value;
    }

    /**
     * Gets the value of the discountsCompetitors property.
     * 
     */
    public int getDiscountsCompetitors() {
        return discountsCompetitors;
    }

    /**
     * Sets the value of the discountsCompetitors property.
     * 
     */
    public void setDiscountsCompetitors(int value) {
        this.discountsCompetitors = value;
    }

    /**
     * Gets the value of the advCompaniesCompetitors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvCompaniesCompetitors() {
        return advCompaniesCompetitors;
    }

    /**
     * Sets the value of the advCompaniesCompetitors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvCompaniesCompetitors(String value) {
        this.advCompaniesCompetitors = value;
    }

    /**
     * Gets the value of the promoBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoBrand() {
        return promoBrand;
    }

    /**
     * Sets the value of the promoBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoBrand(String value) {
        this.promoBrand = value;
    }

}
