//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:39:05 PM NOVT 
//


package ru.develop.anketamanager.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnketaAdditionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnketaAdditionInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ToOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExpressDeliveries" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AmountDeliveries" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="IntroProductLines" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TrainingSeminar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnketaAdditionInfo", propOrder = {

})
public class AnketaAdditionInfo {

    @XmlElement(name = "ToOrder", required = true)
    protected String toOrder;
    @XmlElement(name = "ExpressDeliveries")
    protected int expressDeliveries;
    @XmlElement(name = "AmountDeliveries", required = true)
    protected BigDecimal amountDeliveries;
    @XmlElement(name = "IntroProductLines")
    protected int introProductLines;
    @XmlElement(name = "TrainingSeminar", required = true)
    protected String trainingSeminar;

    /**
     * Gets the value of the toOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToOrder() {
        return toOrder;
    }

    /**
     * Sets the value of the toOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToOrder(String value) {
        this.toOrder = value;
    }

    /**
     * Gets the value of the expressDeliveries property.
     * 
     */
    public int getExpressDeliveries() {
        return expressDeliveries;
    }

    /**
     * Sets the value of the expressDeliveries property.
     * 
     */
    public void setExpressDeliveries(int value) {
        this.expressDeliveries = value;
    }

    /**
     * Gets the value of the amountDeliveries property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountDeliveries() {
        return amountDeliveries;
    }

    /**
     * Sets the value of the amountDeliveries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountDeliveries(BigDecimal value) {
        this.amountDeliveries = value;
    }

    /**
     * Gets the value of the introProductLines property.
     * 
     */
    public int getIntroProductLines() {
        return introProductLines;
    }

    /**
     * Sets the value of the introProductLines property.
     * 
     */
    public void setIntroProductLines(int value) {
        this.introProductLines = value;
    }

    /**
     * Gets the value of the trainingSeminar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainingSeminar() {
        return trainingSeminar;
    }

    /**
     * Sets the value of the trainingSeminar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainingSeminar(String value) {
        this.trainingSeminar = value;
    }

}
