//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:39:05 PM NOVT 
//


package ru.develop.anketamanager.xml;

//import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.develop.anketa.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
//@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.develop.anketa.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnketaProductInfoExt }
     * 
     */
    public AnketaProductInfoExt createAnketaProductInfoExt() {
        return new AnketaProductInfoExt();
    }

    /**
     * Create an instance of {@link AnketaMarketInfo }
     * 
     */
    public AnketaMarketInfo createAnketaMarketInfo() {
        return new AnketaMarketInfo();
    }

    /**
     * Create an instance of {@link VisitPurpose }
     * 
     */
    public VisitPurpose createVisitPurpose() {
        return new VisitPurpose();
    }

    /**
     * Create an instance of {@link AnketaAdditionInfo }
     * 
     */
    public AnketaAdditionInfo createAnketaAdditionInfo() {
        return new AnketaAdditionInfo();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Anketa }
     * 
     */
    public Anketa createAnketa() {
        return new Anketa();
    }

    /**
     * Create an instance of {@link ActivityKind }
     * 
     */
    public ActivityKind createActivityKind() {
        return new ActivityKind();
    }

    /**
     * Create an instance of {@link AnketaProductInfo }
     * 
     */
    public AnketaProductInfo createAnketaProductInfo() {
        return new AnketaProductInfo();
    }

}
