//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:39:05 PM NOVT 
//


package ru.develop.anketamanager.xml;

import java.io.Serializable;
import java.util.List;

//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for References complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="References">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Regions" type="{http://tempuri.org/XMLSchema.xsd}Region" minOccurs="0"/>
 *         &lt;element name="Activities" type="{http://tempuri.org/XMLSchema.xsd}ActivityKind" minOccurs="0"/>
 *         &lt;element name="VisitPurposes" type="{http://tempuri.org/XMLSchema.xsd}VisitPurpose" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "References", propOrder = {

//})
public class References  implements Serializable{

   // @XmlElement(name = "Regions")
    protected List<Region> regions;
   // @XmlElement(name = "Activities")
    protected List<ActivityKind> activities;
   // @XmlElement(name = "VisitPurposes")
    protected List<VisitPurpose> visitPurposes;

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link Region }
     *     
     */
    public List<Region> getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Region }
     *     
     */
    public void setRegions(List<Region> value) {
        this.regions = value;
    }

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityKind }
     *     
     */
    public List<ActivityKind> getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityKind }
     *     
     */
    public void setActivities(List<ActivityKind> value) {
        this.activities = value;
    }

    /**
     * Gets the value of the visitPurposes property.
     * 
     * @return
     *     possible object is
     *     {@link VisitPurpose }
     *     
     */
    public List<VisitPurpose> getVisitPurposes() {
        return visitPurposes;
    }

    /**
     * Sets the value of the visitPurposes property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitPurpose }
     *     
     */
    public void setVisitPurposes(List<VisitPurpose> value) {
        this.visitPurposes = value;
    }

}
