//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 02:39:05 PM NOVT 
//


package ru.develop.anketamanager.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisitPurpose complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisitPurpose">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Код" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Наименование" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisitPurpose", propOrder = {

})
public class VisitPurpose {

    @XmlElement(name = "\u041a\u043e\u0434", required = true)
    protected Object код;
    @XmlElement(name = "\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435", required = true)
    protected Object наименование;

    /**
     * Gets the value of the код property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getКод() {
        return код;
    }

    /**
     * Sets the value of the код property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setКод(Object value) {
        this.код = value;
    }

    /**
     * Gets the value of the наименование property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getНаименование() {
        return наименование;
    }

    /**
     * Sets the value of the наименование property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setНаименование(Object value) {
        this.наименование = value;
    }

}
